In [15]:
#https://archive-beta.ics.uci.edu/dataset/2/adult

url <- "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"

download.file(url, "data/raw/adult_raw.csv", mode = "wb")

url_2 <- "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.names"
download.file(url_2, "data/raw/adult_names_raw.csv", mode = "wb")

In [18]:
adult_raw <- read.csv("data/raw/adult_raw.csv", 
                        header = FALSE,
                        na.strings = "?")
colnames(adult_raw) <- c("age", "workclass", "fnlwgt", "education", "education_num",
                        "marital_status", "occupation", "relationship", "race", "sex",
                        "capital_gain", "capital_loss", "hours_per_week", "native_country", "income")
head(adult_raw)

  age workclass         fnlwgt education  education_num marital_status
1 39   State-gov         77516  Bachelors 13             Never-married
2 50   Self-emp-not-inc  83311  Bachelors 13             Married-civ-spouse
3 38   Private          215646  HS-grad    9             Divorced
4 53   Private          234721  11th       7             Married-civ-spouse
5 28   Private          338409  Bachelors 13             Married-civ-spouse
6 37   Private          284582  Masters   14             Married-civ-spouse
  occupation         relationship   race   sex     capital_gain capital_loss
1  Adm-clerical       Not-in-family  White  Male   2174         0
2  Exec-managerial    Husband        White  Male      0         0
3  Handlers-cleaners  Not-in-family  White  Male      0         0
4  Handlers-cleaners  Husband        Black  Male      0         0
5  Prof-specialty     Wife           Black  Female    0         0
6  Exec-managerial    Wife           White  Female    0         0
  hours_per_week native_country income
1 40              United-States  <=50K
2 13              United-States  <=50K
3 40              United-States  <=50K
4 40              United-States  <=50K
5 40              Cuba           <=50K
6 40              United-States  <=50K

In [84]:
unique(adult_raw$income)

[1] " <=50K" " >50K"

In [ ]:
#Note: there are some missing values from workclass, occupation
# unique(adult_raw$marital_status)
adult_processed <- adult_raw |> filter(workclass != " Never-worked" & #filtering those that never worked as its all below 50k
                                        workclass != " ?" &  #removing missing values
                                        occupation != " ?" &
                                        native_country != " ?") |>
                                mutate(married = ifelse(marital_status != " Widowed" & 
                                                        marital_status != " Never-married", 
                                                        1, 0))|>
                                mutate(male = ifelse(sex == " Male", 
                                                        1, 0))|>
                                mutate(race_white = ifelse(race == " White", 
                                                        1, 0))|>
                                mutate(race_asian_pac_islander = ifelse(race == " Asian-Pac-Islander", 
                                                        1, 0))|>
                                mutate(race_amer_indian_eskimo = ifelse(race == " Amer-Indian-Eskimo", 
                                                        1, 0))|>
                                mutate(race_black = ifelse(race == " Black", 
                                                        1, 0))|>
                                mutate(race_other = ifelse(race == " Other", 
                                                        1, 0))|>
                                mutate(income = ifelse(income == " >50K", 
                                                        1, 0))|>
                                select(-education, -fnlwgt, -marital_status, 
                                        -workclass, -occupation, -relationship,
                                        -race, -sex)
head(adult_processed)

#explanation on variables
#income = 1 if over 50k
#married = 1 if not devorced or never married (widowed counts as married)

write.csv(adult_processed, "data/processed/adult_processed.csv", row.names = FALSE)

  age education_num capital_gain capital_loss hours_per_week native_country
1 39  13            2174         0            40              United-States
2 50  13               0         0            13              United-States
3 38   9               0         0            40              United-States
4 53   7               0         0            40              United-States
5 28  13               0         0            40              Cuba
6 37  14               0         0            40              United-States
  income married male race_white race_asian_pac_islander
1 0      0       1    1          0
2 0      1       1    1          0
3 0      1       1    1          0
4 0      1       1    0          0
5 0      1       0    0          0
6 0      1       0    1          0
  race_amer_indian_eskimo race_black race_other
1 0                       0          0
2 0                       0          0
3 0                       0          0
4 0                       1          0
5 0                       1          0
6 0                       0          0